### ISSUE TITLE
Report names are mixed after API change to BIR 1.1

### ISSUE THREAD

**Issue by krzyc** [johnzuk/GusApi#100]
After updating API to BIR 1.1 some report types are mixed in comparsion with BIR 1.0 based versions:

    public const REPORT_LOCALS_PHYSIC_PUBLIC = 'BIR11OsFizycznaPkd';
    public const REPORT_LOCAL_PHYSIC_PUBLIC = 'BIR11OsFizycznaListaJednLokalnych';
    public const REPORT_ACTIVITY_PHYSIC_PUBLIC = 'BIR11JednLokalnaOsFizycznej';

It should look like this:

    public const REPORT_LOCALS_PHYSIC_PUBLIC = 'BIR11OsFizycznaListaJednLokalnych';
    public const REPORT_LOCAL_PHYSIC_PUBLIC = 'BIR11JednLokalnaOsFizycznej';
    public const REPORT_ACTIVITY_PHYSIC_PUBLIC = 'BIR11OsFizycznaPkd';

In my opinion current report naming is not consistent and I will opt for a change in upcoming versions. We can keep current constants with deprecation mark and add a new set - my proposal is:

    public const REPORT_PHYSIC = 'BIR11OsFizycznaDaneOgolne';
    public const REPORT_PHYSIC_CEIDG = 'BIR11OsFizycznaDzialalnoscCeidg';
    public const REPORT_PHYSIC_AGRO = 'BIR11OsFizycznaDzialalnoscRolnicza';
    public const REPORT_PHYSIC_OTHER = 'BIR11OsFizycznaDzialalnoscPozostala';
    public const REPORT_PHYSIC_DELETED_BEFORE_20141108 = 'BIR11OsFizycznaDzialalnoscSkreslonaDo20141108';
    public const REPORT_PHYSIC_LOCALS = 'BIR11OsFizycznaListaJednLokalnych';
    public const REPORT_PHYSIC_LOCAL = 'BIR11JednLokalnaOsFizycznej';
    public const REPORT_PHYSIC_ACTIVITY = 'BIR11OsFizycznaPkd';
    public const REPORT_PHYSIC_LOCAL_ACTIVITY = 'BIR11JednLokalnaOsFizycznejPkd';
    public const REPORT_LAW = 'BIR11OsPrawna';
    public const REPORT_LAW_ACTIVITY = 'BIR11OsPrawnaPkd';
    public const REPORT_LAW_LOCALS = 'BIR11OsPrawnaListaJednLokalnych';
    public const REPORT_LAW_LOCAL = 'BIR11JednLokalnaOsPrawnej';
    public const REPORT_LAW_LOCAL_ACTIVITY = 'BIR11JednLokalnaOsPrawnejPkd';
    public const REPORT_LAW_PARTNERS = 'BIR11OsPrawnaSpCywilnaWspolnicy';
    public const REPORT_UNIT_TYPE = 'BIR11TypPodmiotu';

I can submit a PR for my proposal.

**Comment by johnzuk** [comment]
Hi, feel free to add proper PR :) i will take a look on it later

**Comment by chilek** [comment]
My 3 cents to discussion - "osoba prawna" translates to "legal person/entity" to better use `LEGAL` than `LAW` ;-)
Bests!

**Comment by krzyc** [comment]
`PHYSIC` is also strange. Maybe `PERSON` and `ORGANIZATION` are more correct.

**Comment by chilek** [comment]
> `PHYSIC` is also strange. Maybe `PERSON` and `ORGANIZATION` are more correct.

PERSON is much better, but maybe PRIVATE?
