### ISSUE TITLE
REPORT_PERSON_ACTIVITY nie zwraca pkd tylko zawsze że nie znaleziono wpisu

### ISSUE THREAD

**Issue by pawel-dubiel** [johnzuk/GusApi#102]
REPORT_PERSON_ACTIVITY zawsze zwraca error coe dla osób fizycznych. Nie wiem czy tego sie mam spodziewać.
```    [0] => Array
        (
            [ErrorCode] => 4
            [ErrorMessagePl] => Nie znaleziono wpisu dla podanych kryteriów wyszukiwania.
            [ErrorMessageEn] => No data found for the specified search criteria.
            [pRegon] => tutaj regon number
            [Typ_podmiotu] => 
            [Raport] => BIR11OsFizycznaPkd
        )
```

**Comment by pawel-dubiel** [comment]
co ciekawe dla osób fizycznych ten raport 
`    public const REPORT_ORGANIZATION_ACTIVITY = 'BIR11OsPrawnaPkd';`
zwraca liste pkd

**Comment by Qrzysio** [comment]
Wydaje mi się, że ten problem był już poruszany. Opiszę krótko jako podsumowanie.

Osoby fizyczne w przeszłości miały nadawane NIP, gdy szły do pracy lub otwierały działalność. Od kilku lat NIP nadawany jest wyłącznie osobom, które zakładają działalność. Pracownicy firm  posługują się co najwyżej numerem PESEL.

W ubiegłym roku pisałem w #96 o firmie bez adresu. to eden z tych przypadków. Niestety GUS bazuje na numerach REGON, a te są ściśle powiązane z działalnością. Więc przy jednoosobowych działalnościach gospodarczych musimy bazować na numerach NIP i rejestrze CEIDG (firma.gov.pl). Ten system ma swoje API (https://datastore.ceidg.gov.pl). Należy się zarejestrować i pobrać klucz. Miał ruszyć nowy serwis rządowy, ale do tej pory nie ruszył. W każdej chwili może się to jednak zmienić, więc piszę to dla potomnych.

Proszę zapoznajcie się także z #90. Tam jest poruszony jeden z wyjątków.

W sprawach danych zwracanych p[rzez API GUS warto wysłać e-mail do GUS. Odpowiadają rzeczowo i szybko, polecam.

**Comment by weclaprz** [comment]
Witam, chciałbym krótko podzielić się spostrzeżeniami.
Z Api do GUS korzystam w 2 miejscach. Jedna to aplikacja napisana w C# druga w PHP.
O ile w aplikacji C# raport BIR11OsFizycznaPkd działa bez problemu i zwraca wartości zgodnie z dokumentacją api.
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema id="BIR11OsFizycznaPkd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
		<xs:element name="dane" minOccurs="0" maxOccurs="unbounded">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="fiz_pkd_Kod" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="5"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="fiz_pkd_Nazwa" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="200"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="fiz_pkd_Przewazajace" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="fiz_SilosID" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:int">
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="fiz_Silos_Symbol" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="fiz_dataSkresleniaDzialalnosciZRegon" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:date">
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	    </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

**Comment by weclaprz** [comment]
Poszukałem, popatrzyłem i znalazłem przyczynę.
W pliku ReportTypes.php brakuje dla tablicy REGON_9_REPORTS wpisu  self::REPORT_PERSON_ACTIVITY,
Brak tego wpisu powoduje że weryfikacja nazw raportów w api w pliku ReportRegonNumberMapper.php funkcji getRegonNumberByReportName zwraca false.

**Comment by johnzuk** [comment]
Sprawdzę ten case - i dodam fixa :)

**Comment by pgarnek** [comment]
hej @johnzuk , udało Ci się już na to spojrzeć? :]

**Comment by johnzuk** [comment]
Dodałem MR zgodnie z opisem ale nie miałem czasu tego przetestować niestety https://github.com/johnzuk/GusApi/pull/107 @pgarnek jesteś w stanie zweryfikować czy fix który zaproponował @weclaprz jest ok ?
