### ISSUE TITLE
Usługa DaneSzukajPodmioty zwraca tekst pusty, wyjątek No data found

### ISSUE THREAD

**Issue by jtomkowiak** [johnzuk/GusApi#105]
Paczka zainstalowana na projekcie Symfony 4
Php 7.3.28
Projekt w kontenerze Docker-a
Nie wykazuje żadnych błędów w kodzie php.
Jednak mimo prawidłowego parametru NIP nie zwraca danych.
Jeśli w pliku GusApiClient.php 
testowo zamiast 
              **return $this->soapClient->__soapCall($functionName, $arguments, [], $soapHeaders);**
wstawię
            **dump($this->soapClient->__soapCall($functionName, $arguments, [], $soapHeaders));
            dump ($this->soapClient->__getLastRequest ());
            dump ($this->soapClient->__getLastResponse ());**
to otrzymam
**Request:**
_<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://CIS/BIR/PUBL/2014/07/DataContract" xmlns:ns2="http://CIS/BIR/PUBL/2014/07" xmlns:ns3="http://www.w3.org/2005/08/addressing"><env:Header><ns3:Action>http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajPodmioty</ns3:Action><ns3:To>https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc</ns3:To></env:Header><env:Body><ns2:DaneSzukajPodmioty><ns2:pParametryWyszukiwania><ns1:Krs xsi:nil="true"/><ns1:Krsy xsi:nil="true"/><ns1:Nip>7772976791</ns1:Nip><ns1:Nipy xsi:nil="true"/><ns1:Regon xsi:nil="true"/><ns1:Regony14zn xsi:nil="true"/><ns1:Regony9zn xsi:nil="true"/></ns2:pParametryWyszukiwania></ns2:DaneSzukajPodmioty></env:Body></env:Envelope>_
**Response**
_<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><a:Action s:mustUnderstand="1">http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajPodmiotyResponse</a:Action></s:Header><s:Body><DaneSzukajPodmiotyResponse xmlns="http://CIS/BIR/PUBL/2014/07"><DaneSzukajPodmiotyResult/></DaneSzukajPodmiotyResponse></s:Body></s:Envelope>_

Czyli w zasadzie poprawna składniowo odpowiedź tylko brak zwracanych danych

**Comment by Qrzysio** [comment]
Podaj ten numer NIP.

**Comment by jtomkowiak** [comment]
7772976791

**Comment by jtomkowiak** [comment]
Sprawa się wyjaśniła. Przyczyną był nieaktualny certyfikat ssl.
Wszystko działa
Zamykam temat.
