### ISSUE TITLE
Brak inicjalizacji GusApi::$sessionId

### ISSUE THREAD

**Issue by ppoz21** [johnzuk/GusApi#115]
Metoda `GusApi::isLogged()` korzysta z metody `GusApi::getSessionStatus()`.

W metodzie  `GusApi::getSessionStatus()` mamy fragment

```php
public function getSessionStatus(): int
{
    $response = $this->apiClient->getValue(
        new GetValue(ParamName::SESSION_STATUS),
        $this->sessionId
    );

    return (int) $response->getGetValueResult();
}
```

natomiast deklaracja property `GusApi::$sessionId` wygląda następująco:

```php
private string $sessionId;
```

Takie rozwiązanie powoduje Exception w momencie wywołania metody `GusApi::isLogged()`  przed wywołaniem `GusApi::login()`.

Rozwiązaniem może być inicjalizacja  `GusApi::$sessionId` poprzez pusty string lub użycie `try...catch` w `GusApi::getSessionStatus()` - zwracanie 0 przy wystąpieniu Exception

**Comment by IonBazan** [comment]
Wg mnie powinnismy sprawdzać przed wywołaniem `isset($this->sessionId` ale zamiast zwracać 0, powinnismy rzucić własnym customowym wyjatkiem (że należy zawołać `login()` przed wywołaniem tej metody)

**Comment by ppoz21** [comment]
@IonBazan 
Moja propozycja zwracania 0 wynika z wywołania `GusApi::getSessionStatus()` w `GusApi::isLogged()`. Raczej sprawdzając czy jestem zalogowany nie chciałbym dostać wyjątku "Zaloguj się, żeby sprawdzić czy jesteś zalogowany". Tak na prawdę równie dobrze mógłby być `return false;` w `GusApi::isLogged()` jeśli nie istnieje `$this->sessionId`

**Comment by johnzuk** [comment]
Najlepiej pewnie było bo zrobić jak @IonBazan pisze czyli sprawdzać i rzucać wyjątek wszędzie tam gdzie metoda login jest wymagana. Bo podobnie będzie przy wywołaniu jakiejkolwiek innej metody która wymaga istnienia `sessionId` Metoda `isLogin` to po prostu nazwa angielska metody z API, która de facto sprawdza czy sesja API jest aktywna, dlatego wymaga `sessionId`. Co w tym kontekście ma oczywiście sens. Ale za to nazwa metody może być myląca

**Comment by IonBazan** [comment]
Faktycznie `isLogged()` mógłby uprzednio sprawdzać czy `sessionId` został ustawiony - jeśli nie, zwracać od razu `false`.
Do pozostałych metod możnaby dodać wywołanie `ensureHasSession()`, która rzucałaby wyjątek gdy nie ustawiono ID sesji. 

Na szybko sprawę załatwiłoby ustawienie sesji jako pusty string jak @ppoz21 wyżej wspomniał.

**Comment by IonBazan** [comment]
@ppoz21 daj znać, czy implementacja w #116 spełnia Twoje oczekiwania 😉

**Comment by ppoz21** [comment]
@IonBazan 
Jak dla mnie idealnie 😃
