### ISSUE TITLE
GusApi::setSessionId removed

### ISSUE THREAD

**Issue by hubipe** [johnzuk/GusApi#117]
Hello,
I've upgraded to version 6, and found out, that the method GusApi::setSessionId has been removed. I used to cache the session ID for 55 minutes in server local storage, so the session ID didn't have to regenerate every time the API was called in separate request.
Is there a way, how to cache session ID in version 6 so the program don't have to call login method every time?

Thanks

**Comment by johnzuk** [comment]
Shame I didn't think of that 😅 
Probably add this missing method and release bugfix version 6.1.1 should be enough i think, like so
https://github.com/johnzuk/GusApi/pull/118

**Comment by johnzuk** [comment]
I've released version 6.1.1 with added back method `GusApi::setSessionId` please upgrade to it and should be fine :)

**Comment by hubipe** [comment]
@johnzuk Thank you very much for the prompt release :)
