### ISSUE TITLE
Wyszukiwarka danych

### ISSUE THREAD

**Issue by masztan** [johnzuk/GusApi#12]
Drobnym mankamentem jest to, że wyszukiwarka zwraca tylko pierwsze wystąpienie działalności gospodarczej. Natomiast czasami występuje ich więcej.
Musiałem przerobić kod metody search z:

private function search($sid, array $searchData)
    {
        try{
            $response = $this->adapter->search($sid, $searchData);
        } catch (NoDataException $e) {
            throw new NotFoundException(sprintf("Not found subject"));
        }
        return new SearchReport($response[0]);
    }

na:

private function search($sid, array $searchData)
    {
        try{
            $response = $this->adapter->search($sid, $searchData);
        } catch (NoDataException $e) {
            throw new NotFoundException(sprintf("Not found subject"));
        }
        $return = array();
        foreach($response as $resp){
            $return[] = new SearchReport($resp);
        }
        return $return;
    }

**Comment by johnzuk** [comment]
Dzięki za cenne uwagi :+1: - zmiany wrzuciłem na mastera - zgłoszenie zamykam
