### ISSUE TITLE
Upgrade z 5.3 do 6.1

### ISSUE THREAD

**Issue by Buzka91** [johnzuk/GusApi#120]
W [wersji 6.0](https://github.com/johnzuk/GusApi/compare/5.3.0...6.0.0#diff-e0a19d5b11a11c3b035512ad8b0225451e7c38aa69342157225b6ea504cf311bR36-R37) nastąpiła zmiana modyfikatora dostępu dla propertisa `$apiClient` oraz [samego dostępu do SoapClienta](https://github.com/johnzuk/GusApi/compare/5.3.0...6.0.0#diff-04c210af7ee2f1864e2198f0ec90ef16488503592b6a6748a5dae68134271cbbR30).

Każde zapytanie logujemy u nas wewnętrznie (request, response, czas odpowiedzi etc.) bez dostępu do SoapClienta nie jesteśmy w stanie się zmigrować do nowszej wersji. Czy jest jakiś powód czemu nie zostało to udostępnione?

```php
$lastRequest = $this->apiClient->getSoapClient()->__getLastRequest();
$lastResponse = $this->apiClient->getSoapClient()->__getLastResponse();
```

**Comment by johnzuk** [comment]
Idea była taka żeby stworzyć jakiś sensowny request logger interface który umożliwiał by wstrzyknięcie się z loggerem.
Z uwagi na ograniczone zasoby czasowy nie byłem w stanie tego jeszcze zrobić :(
Można przywrócić opcję pobrania clienta i wypuścić nową wersję zanim nastąpi zmiana
PR mile widziany :)

**Comment by artur-mietek** [comment]
W nawiązaniu do pytania Buzka91 stworzyłem PR https://github.com/johnzuk/GusApi/pull/122

**Comment by johnzuk** [comment]
@Buzka91 możesz zrobić review tych zmian - wydaje, się, że to to czego potrzebujesz :)

**Comment by johnzuk** [comment]
close by #122
