### ISSUE TITLE
street number not visible

### ISSUE THREAD

**Issue by rawaby88** [johnzuk/GusApi#13]
every thing works as excepted,  but the street address display one the street name without number
 - how i can get full address?
Thanks You

**Comment by johnzuk** [comment]
Try to change `ReportTypes::REPORT_ACTIVITY_LAW_PUBLIC` to  `ReportTypes::REPORT_PUBLIC_LAW` and then the report will have key **praw_adSiedzNumerNieruchomosci** with  street number
