### ISSUE TITLE
User key & SSL certificate fails

### ISSUE THREAD

**Issue by requtize** [johnzuk/GusApi#14]
Where I can get user key to use this API without problems?

-------------------

Other problem I have, that scrips throws with belowed error, any ideas why?

> SoapClient::SoapClient(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by johnzuk** [comment]
You have to contact via email regon_bir@stat.gov.pl and send information about your company:
REGON number etc.

From official doc.
W celu uzyskania Klucza Użytkownika do środowiska produkcyjnego prosimy o przesłanie na
adres email regon_bir@stat.gov.pl wiadomości zawierającej następujące informacje:

Pełna nazwa podmiotu
Numer REGON podmiotu
Imię i nazwisko osoby do kontaktu
Adres email osoby do kontaktu
Numer telefonu stacjonarny
Numer telefonu komórkowy
Adresy IP, z których będą się komunikowały Państwa systemy teleinformatyczne (Dotyczy
sytuacji gdy użytkownicy końcowi będą łączyć się z BIR1 poprzez serwer dostępowy dostawcy
oprogramowania -punkt 2.6.3 "Instrukcji technicznej" pt. "Zalecana architektura"). Ponadto
w przypadku gdy adres/pula adresów IP jest stała - zalecamy podanie tych adresów dla celów
diagnostycznych podczas ew. kłopotów z korzystaniem z Usługi.
Informacja o przewidywanej łącznej liczbie zapytań w skali miesiąca (w przypadku kłopotów
z oszacowaniem – prosimy okreslić przynajmniej rząd wielkości).

**Comment by requtize** [comment]
Caused by Client Server SSL issue.
