### ISSUE TITLE
Street without number of building

### ISSUE THREAD

**Issue by LiderParking** [johnzuk/GusApi#16]
I received data from GUS, but without number of building. 

'array(1) {
  [0] =>
  class GusApi\SearchReport#105124 (11) {
    private $regon =>
    class SimpleXMLElement#105135 (1) {
      public ${0} =>
      string(14) "36301807100000"
    }
    private $regon14 =>
    string(14) "36301807100000"
    private $name =>
    class SimpleXMLElement#105127 (1) {
      public ${0} =>
      string(59) "SERWIS PARKING SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ"
    }
    private $province =>
    class SimpleXMLElement#105121 (1) {
      public ${0} =>
      string(11) "MAZOWIECKIE"
    }
    private $district =>
    class SimpleXMLElement#105125 (1) {
      public ${0} =>
      string(15) "m. st. Warszawa"
    }
    private $community =>
    class SimpleXMLElement#105122 (1) {
      public ${0} =>
      string(4) "Wola"
    }
    private $city =>
    class SimpleXMLElement#105120 (1) {
      public ${0} =>
      string(8) "Warszawa"
    }
    private $zipCode =>
    class SimpleXMLElement#105119 (1) {
      public ${0} =>
      string(6) "00-844"
    }
    private $street =>
    class SimpleXMLElement#105118 (1) {
      public ${0} =>
      string(14) "ul. Grzybowska"
    }
    private $type =>
    string(1) "p"
    private $silo =>
    class SimpleXMLElement#105116 (1) {
      public ${0} =>
      string(1) "6"
    }
  }
}
`

**Comment by johnzuk** [comment]
Try to change `ReportTypes::REPORT_ACTIVITY_LAW_PUBLIC` to `ReportTypes::REPORT_PUBLIC_LAW` and then the report will have key **praw_adSiedzNumerNieruchomosci** with street number
