### ISSUE TITLE
Wrong BASE_WSDL_URL

### ISSUE THREAD

**Issue by Wirone** [johnzuk/GusApi#17]
I've installed package (06962d8) and there is, I think, wrong value for BASE_WSDL_URL.

```php
interface RegonConstantsInterface
{
    const BASE_WSDL_URL_TEST = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd';
    const BASE_WSDL_ADDRESS_TEST =  'https://Wyszukiwarkaregontest.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc';

    const BASE_WSDL_URL = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd';
    const BASE_WSDL_ADDRESS =  'https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc';

    // ...
}
```

There is `wyszukiwarkaregontest` (test!) in `BASE_WSDL_URL`.

**Comment by Wirone** [comment]
Now I see that https://wyszukiwarkaregon.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd is not found.. Test definition must be used for production usage?

**Comment by johnzuk** [comment]
https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd is only a file with data structure definition. Server location is https://wyszukiwarkaregon.stat.gov.pl/wsBIR/UslugaBIRzewnPubl.svc everything is fine ;)

**Comment by Wirone** [comment]
Yeah, I was just wondering if it's OK to use structure definition from test URL with production service. If this test definition is always valid for production service, then no problem.

**Comment by johnzuk** [comment]
Yes this definition is always valid for production ;)
