### ISSUE TITLE
Numer ulicy, zmiana raportu na REPORT_PUBLIC_LAW

### ISSUE THREAD

**Issue by arturosinski** [johnzuk/GusApi#21]
Problem z otrzymaniem numeru ulicy i zmiana raportu.
Przejrzałem wcześniejsze problemy z brakiem numeru ulicy gdzie podpowiadałeś aby zmeinić
raport z ReportTypes::REPORT_ACTIVITY_LAW_PUBLIC na ReportTypes::REPORT_PUBLIC_LAW.
Zmiany dokonuję w getFromNip.php , przykładzie.
ReportTypes::REPORT_ACTIVITY_LAW_PUBLIC, działa bez problemu.
```
var_dump(
      $gus->getFullReport(
       $_SESSION['sid'],
        $gusReport[0],
        ReportTypes::REPORT_ACTIVITY_LAW_PUBLIC
 )
```
Zmieniam raport na : ReportTypes::REPORT_PUBLIC_LAW i Fatal error:

> Fatal error: Uncaught exception 'GusApi\Adapter\Soap\Exception\NoDataException' with message 'No data found' in /Testy/GusApi/Adapter/Soap/SoapAdapter.php:122 Stack trace: #0 ... 

> 
Czego to może być problem ? So inne metody niz getFullReport ?

**Comment by johnzuk** [comment]
Czy klucz API użyty w tym wypadku pozwala na dostęp do tego raportu? W zależności od potrzeby, przydzielane są klucze z różnymi prawami dostępu do raportów.

**Comment by arturosinski** [comment]
Witam.
Dziś otrzymałem klucz, zweryfikuję ponownie i dam znać.
Obecny problem dotyczył pracy na kluczu testowym zawartym w oprogramowaniu.

**Comment by johnzuk** [comment]
Czy problem udało się rozwiązać?

**Comment by arturosinski** [comment]
Jeszcze nie miałem okazji przetestować. Zostałem chwilowo oddelegowany do innego zadania. 
Proszę jeszcze o 2 dni i dam znać.

**Comment by arturosinski** [comment]
Witam. Mam klucz komercyjny, po zarejestrowaniu się. Jednak probelm dalej występuje.
Środowisko zmieniłem na normalne z testowego. Autoryzacja przebiegła poprawnie, jednak po zmienie typu raportu na REPORT_PUBLIC_LAW , dalej jest błąd.
```
`var_dump(
                    $gus->getFullReport(
                        $_SESSION['sid'],
                        $gusReport[0],
                        ReportTypes::REPORT_PUBLIC_LAW
                    )
                );`
```

> Fatal error: Uncaught exception 'GusApi\Adapter\Soap\Exception\NoDataException' with message 'No data found' in /Testy/GusApi/Adapter/Soap/SoapAdapter.php:123 Stack trace: #0 /Testy/GusApi/GusApi.php(195): GusApi\Adapter\Soap\SoapAdapter->getFullData('numer_sid...', '07036295800000', 'PublDaneRaportP...') #1 /Testy/getFromNip.php(73): GusApi\GusApi->getFullReport('numer_sid...', Object(GusApi\SearchReport), 'PublDaneRaportP...') #2 {main} thrown in /Testy/GusApi/Adapter/Soap/SoapAdapter.php on line 123

Podmieniłem tylko sid na numer_sid. Jakiś pomysł ?

**Comment by johnzuk** [comment]
Nie jest to błąd, a wyjątek występujący podczas braku danych, proszę spróbować dla nip-u 5250007738
Dla klucza który posiadam raport jest dostępny i generuje się prawidłowo

**Comment by robertpustulka** [comment]
To chyba zależy od rodzaju działalności.

Ja sprawdzam te dwa raporty i wyciągam nr ulicy z jednego z nich:

```php
        $types = [
            ReportTypes::REPORT_ACTIVITY_PHYSIC_CEGID => 'fiz_adSiedzNumerNieruchomosci',
            ReportTypes::REPORT_PUBLIC_LAW => 'praw_adSiedzNumerNieruchomosci'
        ];
        foreach ($types as $type => $field) {
            try {
                return $api->getFullReport($session, $report, $type)->dane->$field;
            } catch (NoDataException $e) {

            }
        }
```

**Comment by robertpustulka** [comment]
BTW teraz zauważyłem, jest błąd w stałej:

`ReportTypes::REPORT_ACTIVITY_PHYSIC_CEGID` powinno być `*_CEIDG` :)

**Comment by arturosinski** [comment]
Dzęki za pomoc. Wszytsko działa , faktycznie nie było danych w raporcie pierwszym.
Nie ogarniam jeszcze do końca php obiektowego więc miałem drobny problem z połapaniem się .
Ale narazie działa.
