### ISSUE TITLE
SoapClient::SoapClient(): SSL operation failed with code 1.

### ISSUE THREAD

**Issue by arcontact** [johnzuk/GusApi#23]
Przydałoby się zmienić metodę _setContextOption (SoapClient.php:100)_ z private na public aby można było dodawać dodatkowe nagłówki dla _stream_context_create()_.

W moim przypadku chciałbym dodać:
```
'ssl' => array(
	'verify_peer'       => false,
	'verify_peer_name'  => false,
)
```

Poradziłem sobie instalując poprawnie certyfikat SSL ale tak czy siak możliwość dodawania extra nagłówków by się przydała.

PS. Świetna biblioteka, zaoszczędziła mi sporo czasu. Dzięki!

**Comment by johnzuk** [comment]
Rzeczywiście, jest to dobry pomysł, w najbliższym czasie wprowadzę stosowne zmiany - dzięki za uwagę :) :+1:
