### ISSUE TITLE
Nie znajduje danych (lub znajduje stare dane)

### ISSUE THREAD

**Issue by daresh** [johnzuk/GusApi#25]
Super biblioteka, testując zauważyłem jednak coś intrygującego - nie znajduje mi danych (np. 9930662817), mimo że firma istnieje i na stronie GUSu da się ją znaleźć. Dla innego NIPu z kolei zwróciło starą nazwę firmy.

O co może chodzić???

**Comment by daresh** [comment]
Chyba już wiem, to serwer testowy pewnie zwraca takie dane :)

**Comment by johnzuk** [comment]
Tak, najprawdopodobniej może chodzić o serwer testowy - proszę spróbować na serwerze produkcyjnym powinno być ok :)
