### ISSUE TITLE
Jak użyć tej biblioteki ?

### ISSUE THREAD

**Issue by micdzi** [johnzuk/GusApi#26]
Witam serdecznie, 
Brakuje informacji w jaki sposób można użyć tej biblioteki. Tzn na samym początku pliku testowego mamy wywołanie `require_once '../vendor/autoload.php';`

Niestety dla początkujących (w tym ja) nie wiadomo skąd wziąć ten plik.
Proszę o pomoc.

**Comment by johnzuk** [comment]
Należy użyć "composera" https://getcomposer.org/

**Comment by Pt47-112** [comment]
Też chciałbym użyć tej biblioteki. Użyłem composera, tworząc jakiś projekt poleceniem znalezionym w sieci, zrobił się plik autoload.php w katalogu vendor, wskazałem go i wywala mi się dalej:

> Fatal error: Uncaught Error: Class 'GusApi\GusApi' not found in C:\app\www\test\gus\examples\getFromNip.php:14 Stack trace: #0 {main} thrown in C:\app\www\test\gus\examples\getFromNip.php on line 14

Co robię źle?

**Comment by johnzuk** [comment]
Po stworzeniu projektu należy jeszcze dodać bibliotekę poprzez: ``composer require gusapi/gusapi``

**Comment by Pt47-112** [comment]
Dziękuję, działa!

**Comment by johnzuk** [comment]
Jako że udało się rozwiązać zamykam zgłoszeni ;)
