### ISSUE TITLE
Możliwość automatycznego dostosowania typu raportu do wykonywanej działalności/jednostki

### ISSUE THREAD

**Issue by MateuszRyaN** [johnzuk/GusApi#28]
Witam,
Tak jak w temacie. Czy jest taka możliwość? W zależności od przypadku przełączać się między **REPORT_ACTIVITY_PHYSIC_PERSON** lub **REPORT_PUBLIC_LAW**.
Czy istnieje jakiś parametr dzięki któremu można typ jednostki i na jej podstawie odwołać się do konkretnej metody?

**Comment by s9029** [comment]
Oczywiście. Jest to opisane w dokumentacji Api GUS-u. Plik PowiazanieRaportTyppodmiotuSilos.docx. Na końcu dokumentu jest opisany dokładny algorytm, wystarczy go przepisać do składni PHP.

**Comment by johnzuk** [comment]
@MateuszRyaN w wersji 3.1 została dodana taka możliwość, został także zmodyfikowany plik przykłady który pokazuje użycie klasy ReportTypeMapper.php
