### ISSUE TITLE
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR

### ISSUE THREAD

**Issue by lukaszflorczak** [johnzuk/GusApi#30]
Przy próbie zalogowania (kod z README) otrzymuję taki błąd:

> Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd' : failed to load external entity "https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd" in /vendor/gusapi/gusapi/src/GusApi/Client/SoapClient.php:32 Stack trace: #0 /vendor/gusapi/gusapi/src/GusApi/Client/SoapClient.php(32): SoapClient->SoapClient('https://wyszuki...', Array) #1 /vendor/gusapi/gusapi/src/GusApi/Adapter/Soap/SoapAdapter.php(45): GusApi\Client\SoapClient->__construct('https://wyszuki...', 'https://Wyszuki...', Array) #2 /gus.php(16): GusApi\Adapter\Soap\SoapAdapter->__construct('ht in /vendor/gusapi/gusapi/src/GusApi/Client/SoapClient.php on line 32

Co może być problemem?

**Comment by johnzuk** [comment]
Może chodzić o parametr allow_url_fopen w konfiguracji php.ini 
![screenshot1](https://user-images.githubusercontent.com/5394761/30985640-2b0b95b0-a491-11e7-9818-46a26b817dc9.png)

**Comment by lukaszflorczak** [comment]
Jest włączony

<img width="984" alt="zrzut ekranu 2017-09-29 o 09 07 20" src="https://user-images.githubusercontent.com/1818979/31004650-8754e100-a4f5-11e7-99d9-42a6545cdf8c.png">

**Comment by lukaszflorczak** [comment]
Najprawdopodobniej aktualizacja do wersji `3.1.1` rozwiązała problem.
