### ISSUE TITLE
More than 1 NIP during one login session

### ISSUE THREAD

**Issue by s9029** [johnzuk/GusApi#35]
Hi,
is it possible to send request about more than 1 NIP during one login session (using one ssid)? Should I login and logout eg. 20 times for the loop of 20 NIPs?

**Comment by johnzuk** [comment]
Hi the REGON server allows to search from 1 to 100 NIP for one request. I am currently working on the addition of this feature to the code

**Comment by johnzuk** [comment]
Hi i add this feature in 3.2. Please notice:
from documentation:
![screenshot1](https://user-images.githubusercontent.com/5394761/34524813-27262c32-f09d-11e7-9681-c96c717d1321.png)
