### ISSUE TITLE
BASE_WSDL_URL w RegonConstantsInterface - pomyłka?

### ISSUE THREAD

**Issue by joca2** [johnzuk/GusApi#42]
W RegonConstantsInterface w linii 9:
const BASE_WSDL_URL = 'https://wyszukiwarkaregontest.stat.gov.pl/wsBIR/wsdl/UslugaBIRzewnPubl.xsd';
czy nie powinno być: https://wyszukiwarkaregon.stat.gov[...]
Fakt, że wyszukiwarkaregon zwraca 404, ale dziwnie wygląda....
Pozdrawiam!
JC

**Comment by johnzuk** [comment]
Hej, jest ok

**Comment by joca2** [comment]
DZIĘKI + pozdrowienia
Jacek
