### ISSUE TITLE
 Catchable fatal error

### ISSUE THREAD

**Issue by wloges** [johnzuk/GusApi#60]
Cześć,
po wywołaniu przykładowego skryptu 

require_once '../vendor/autoload.php';
use GusApi\Exception\InvalidUserKeyException;
use GusApi\GusApi;
use GusApi\ReportTypes;
//$gus = new GusApi('your api key here');
//for development server use:
$gus = new GusApi('abcde12345abcde12345', 'dev');    <--- 8 linia

wywala mi błąd 

Catchable fatal error: Argument 2 passed to GusApi\GusApi::__construct() must be an instance of GusApi\Adapter\AdapterInterface, string given, called in gusapi.php on line 8 and defined in vendor/gusapi/gusapi/src/GusApi/GusApi.php on line 34

Co robię nie tak?

**Comment by wloges** [comment]
Ups, przykład jest PHP 7, a ja mam jeszcze piątkę.

**Comment by johnzuk** [comment]
Hej, tak wygląda suport dla różnych wersji php, wraz z przykładami:

|Version|PHP version |Support                           | Doc  |
|-------|------------|----------------------------------|------|
|4.x    | >= 7.1     | Support ends on December 1, 2019 | [Doc](https://github.com/johnzuk/GusApi/blob/master/README.md)|
|3.3.x  | >= 5.6     | Support ends on December 1, 2018 | [Doc](https://github.com/johnzuk/GusApi/blob/3.3/README.md) |
|3.2.x  | >= 5.4     | Support ended on April 1, 2018   | [Doc](https://github.com/johnzuk/GusApi/blob/3.2/README.md) |
