### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by nemm** [johnzuk/GusApi#63]
`PHP Fatal error: Uncaught TypeError: Return value of GusApi\Type\Response\SearchResponseCompanyData::getWojewodztwo() must be of the type string, null returned in .../GusApi/Type/Response/SearchResponseCompanyData.php:91`

Dosyć nietypowy przypadek, ale jednak. NIP: 7122584951

**Comment by nemm** [comment]
Póki co u siebie użyłem quick fix'a:
`$fields = ['Wojewodztwo','Powiat','Gmina','Miejscowosc','KodPocztowy'];
			foreach( $fields as $field ){
				if( is_null($company->{$field}) ){
					$company->{$field} = '';
				}
			}`

**Comment by johnzuk** [comment]
Hej, dzięki za info postaram się w dziś ogarnąć taki przypadek.

**Comment by johnzuk** [comment]
Hej, niestety nie jestem w stanie powielić tego błędu.
Dla testu:
```
$result = self::$apiClient->getByNip('7122584951');
$this->assertCount(1, $result);
$company = $result[0];

$this->assertSame('LUBELSKIE', $company->getProvince());
```
Wszystko przechodzi poprawnie, możesz napisać coś więcej? 
Np jaka wersja php, jaki branch?

**Comment by nemm** [comment]
Hej, przepraszam, że dopiero teraz odpowiadam. Wersja PHP 7.2. Zdaje się, że dane zostały uzupełnione w GUSie, wcześniej nie było ustawionego województwa. Jak trafię podobny przykład to dam znać.

**Comment by johnzuk** [comment]
ok dzięki za info

**Comment by paulogliwa** [comment]
Dostaję ten sam błąd dla nip: 9462681861
`Return value of GusApi\Type\Response\SearchResponseCompanyData::getWojewodztwo() must be of the type string, null returned`

**Comment by brollypop** [comment]
**Wersja PHP**: 7.1
**Wersja biblioteki**:4.0.0

Podobny problem dla nip: 5941501211 . 

`Type error: Return value of GusApi\Type\Response\SearchResponseCompanyData:
  :getUlica() must be of the type string, null returned`

Nie wiem jak rzadkie są przypadki gdzie brakuje tych danych, ale może warto się zastanowić nad castowaniem danych tak aby zwracana wartość zawsze spełniała interfejs funkcji. Ewentualnie wprowadzić nullable return types `getUlica(): ?string` ale to byłby raczej BC break w stosunku do wersji 4.0.0 .
