### ISSUE TITLE
NAMESPACE w pliku SoapActionMapper

### ISSUE THREAD

**Issue by meeck** [johnzuk/GusApi#72]
Cześć.
w pliku SoapActionMapper jest coś takiego:
public const NAMESPACE = 'http://CIS/BIR/2014/07/IUslugaBIR/';
i to NAMESPACE gryzie się z namespace php. Netbeans zgłasza to jako błąd. 
Oczywiście wystarczy zmienić tą nazwę i problem znika. 
Prośba o poprawkę.
pozdrawiam,
Marek

**Comment by johnzuk** [comment]
To że Netbeans zgłasza to jako błąd nie oznacza, że jest to błąd. Kod działa poprawnie na php >= 7.1
Niema tu czego poprawiać. Jest to jakaś niedoskonałość Netbeansa.

**Comment by meeck** [comment]
Jak tam sobie chcesz. Takie podejście kiedyś się zemści z nawiązką jak nie w tym to w innym projekcie. Pozdrawiam, Marek

**Comment by johnzuk** [comment]
Jak już napisałem wyżej - to nie jest błąd. Netbeansa najwyraźniej nie umie tego ogarnąć - czyli jest to problem po stronie IDE. PHPStorm radzi sobie z tym bez problemu i nie zgłasza żadnych błędów ;)

**Comment by chilek** [comment]
> PHPStorm radzi sobie z tym bez problemu i nie zgłasza żadnych błędów ;)

Potwierdzam, a NetBeans to nędzna namiastka środowiska developerskiego do PHP.

**Comment by meeck** [comment]
No i zaczyna się plucie na środowisko. Opanujcie się! Zgłosiłem tylko nazewnictwo a Wy od razu po środowisku jedziecie. Co za różnica.

**Comment by chilek** [comment]
> No i zaczyna się plucie na środowisko. 

Jakie plucie? To stwierdzenie faktów.

Napisałeś również:

> Takie podejście kiedyś się zemści z nawiązką jak nie w tym to w innym projekcie. 

Skąd wniosek, że to się zemści? ;-)
