### ISSUE TITLE
Fatal error w GusApi.php

### ISSUE THREAD

**Issue by MarcinPHP** [johnzuk/GusApi#73]
Witam,

Przy wywołaniu kodu:
require_once './vendor/autoload.php';
use GusApi\Exception\InvalidUserKeyException;
use GusApi\GusApi;
use GusApi\ReportTypes;
$gus = new GusApi('abcde12345abcde12345', 'dev');

mam taki błąd:
Fatal error: Default value for parameters with a class type hint can only be NULL in \src\GusApi\GusApi.php on line 48

co robie źle ?

**Comment by johnzuk** [comment]
Jaka wersja biblioteki i PHP ?

**Comment by MarcinPHP** [comment]
Dzięki,

po twoim pytaniu lampka mi się zapaliła. 
Mam 4, przełączyłem PHP na  7.1 i wszystko gra

Pozdrawiam
