### ISSUE TITLE
Autoryzacja

### ISSUE THREAD

**Issue by MarcinPHP** [johnzuk/GusApi#74]
Hej,

zarejestrowałem się w stat.gov.pl w celu uzyskania klucza.
Ale dostałem nazwę użytkownika i hasło. Napisali że nie potrzebny jest już klucz do uwierzytelnienia.
Przejrzałem dokumentacje z ich strony i wszędzie jest potrzebny klucz użytkownika.

Potrzebny jest ten klucz czy nie ?

**Comment by chilek** [comment]
Cześć, może to pomoże:
Domyślnie używany jest klucz demo GUS-REGON API. W celu uzyskania Klucza Użytkownika do środowiska produkcyjnego należy przesłać na adres email regon_bir@stat.gov.pl wiadomość zawierającą następujące informacje:

Pełna nazwa podmiotu,
Numer REGON podmiotu,
Imię i nazwisko osoby do kontaktu,
Adres email osoby do kontaktu,
Numer telefonu stacjonarny,
Numer telefonu komórkowy,
Adresy IP, z których będą się komunikowały systemy teleinformatyczne. Ponadto w przypadku gdy adres/pula adresów IP jest stała - zalecane jest podanie tych adresów dla celów diagnostycznych podczas ew. kłopotów z korzystaniem z Usługi,
Informacja o przewidywanej łącznej liczbie zapytań w skali miesiąca (w przypadku kłopotów z oszacowaniem – należy określić przynajmniej rząd wielkości).

**Comment by MarcinPHP** [comment]
Muszę być przemęczony.
Dwa razy sprawdzałem czy na dobry adres wysyłam dane.
A tu masz wysłałem na API TERYT.

Dzięki.
