### ISSUE TITLE
Nowa wersja Api REGON

### ISSUE THREAD

**Issue by masztan** [johnzuk/GusApi#76]
Dostałem informacje o nowej wersji API. Wersja 1.1. Więcej informacji:

https://api.stat.gov.pl/Home/RegonApi

Dobrze by było zaktualizować w bibliotece. :D

**Comment by johnzuk** [comment]
Dzięki za info, pewnie postaram się na dniach dodać zmiany

**Comment by johnzuk** [comment]
#77 - MR
