### ISSUE TITLE
Jak użyskać formę szczególnej prawnej poprzez GusApi?

### ISSUE THREAD

**Issue by Filaro99** [johnzuk/GusApi#79]
Chcę użyskać formę sczególnej prawnej. Czy to jest możliwe? Bo na razie nie znalazłem metody która pobrałaby formę sczególnej prawnej.

**Comment by johnzuk** [comment]
Jeśli dobrze zrozumiałem pytanie, to należy wywołać:
`$fullReport = $gus->getFullReport($gusReport, $reportType);` i użyć innego typu raportu które zdefiniowane są tutaj: [ReportTypes.php](https://github.com/johnzuk/GusApi/blob/master/src/GusApi/ReportTypes.php)
