### ISSUE TITLE
Błąd przy wywołaniu przykładu

### ISSUE THREAD

**Issue by prokicki** [johnzuk/GusApi#80]
Przy wywołaniu pliku z przykładem (poniżejwklejam) wyskakujemi błąd:
Fatal error: Uncaught Error: Class 'GusApi\Client\Builder' not found in /GusApi/GusApi.php:59 Stack trace: #0 /nip.php(11): GusApi\GusApi->__construct('a18a704aac5c4ab...') #1 {main} thrown in /GusApi/GusApi.php on line 59
Wszystkie pliki powinny byc na serwerze.
Podaje adres bezposredni doskopiowanej biblioteki:
https://hosting1981798.online.pro/GusApi/GusApi.php (znajduje się cały skopiowany katalog).

Nie bardzo wiem co robic.

Plik który jest uruchamiany: http://hosting1981798.online.pro/nip.php
<?php

require_once 'GusApi/GusApi.php';

use GusApi\BulkReportTypes;
use GusApi\Exception\InvalidUserKeyException;
use GusApi\Exception\NotFoundException;
use GusApi\GusApi;
use GusApi\ReportTypes;

$gus = new GusApi('a18a704aac.......8e');
//for development server use:
//$gus = new GusApi('abcde12345abcde12345', 'dev');

try {
    $nipToCheck = '5851358017'; //change to valid nip value
    $gus->login();

    $gusReports = $gus->getByNip($nipToCheck);

    var_dump($gus->dataStatus());
    var_dump($gus->getBulkReport(
        new DateTimeImmutable('2019-05-31'),
        BulkReportTypes::REPORT_DELETED_LOCAL_UNITS));

    foreach ($gusReports as $gusReport) {
        //you can change report type to other one
        $reportType = ReportTypes::REPORT_ACTIVITY_PHYSIC_PERSON;
        echo $gusReport->getName();
        echo 'Address: '.$gusReport->getStreet().' '.$gusReport->getPropertyNumber().'/'.$gusReport->getApartmentNumber();

        $fullReport = $gus->getFullReport($gusReport, $reportType);
        var_dump($fullReport);
    }
} catch (InvalidUserKeyException $e) {
    echo 'Bad user key';
} catch (NotFoundException $e) {
    echo 'No data found <br>';
    echo 'For more information read server message below: <br>';
    echo $gus->getResultSearchMessage();
}

**Comment by KamilCwiertnia** [comment]
To mówi wszystko :)
Fatal error: Uncaught Error: Class 'GusApi\Client\Builder' not found

Nie zgadzają ci się ścieżki do biblioteki po prostu

**Comment by prokicki** [comment]
szkopul w tym ze plik z przykladem jest w katalogu w ktorym znajduje sie katalog GusApi pozniej Client i Builder.php

**Comment by prokicki** [comment]
Napisz prosze do mnie na messengerze na facebook przemek.rokicki.sopot szybciej rozwiazemy problem

**Comment by prokicki** [comment]
halo

**Comment by prokicki** [comment]
a teraz taki blad wyskakuje
Warning: PHP Startup: failed to open stream: No such file or directory in /GusApi/nip.php on line 4

Fatal error: PHP Startup: Failed opening required '/vendor/autoload.php' (include_path='.:/:/usr/local/php72/lib/pear') in /GusApi/nip.php on line 4
na kompie u siebie korzystalem z xamp generujac plik autoload. obecnie korzystam z az. pl. o co ich poprosic? :)

**Comment by johnzuk** [comment]
Duplicate of #82
