### ISSUE TITLE
Jakies zmiany zaszły?

### ISSUE THREAD

**Issue by prokicki** [johnzuk/GusApi#84]
Czy zaszły jakies zmiany w oprogramowaniu, albo na serwerach Gusu?
W dniu dzisiejszym odpalamskrypt
http://hosting1981798.online.pro/GusApi/nip.php?nip=5851358017

i pojawia sie błąd:
"Fatal error: PHP Startup: Failed opening required 'phar:///GusApi/vendor/phpstan/phpstan-shim/phpstan.phar/vendor/autoload.php' (include_path='.:/:/usr/local/php72/lib/pear') in /GusApi/vendor/phpstan/phpstan-shim/bootstrap.php on line 8"
mimo, iz dwa dni wczesniej wszystko poprawnie działało.

Pozdrawiam
P.

**Comment by leszcz** [comment]
@prokicki composer dump-autoload
