### ISSUE TITLE
\SoapClient not found

### ISSUE THREAD

**Issue by leszcz** [johnzuk/GusApi#86]
Mam problem z uruchomieniem GusApi u siebie lokalnie. 
Mimo instalacji php-soap (na różnych wersjach PHP, aktualnie 7.3) co chwile wyskakują różne problemy: 
Use of undefined constant SOAP_1_1 - assumed 'SOAP_1_1'
\SoapClient not found

Jakiś pomysł?

**Comment by johnzuk** [comment]
Wygląda, na to że brak rozszerzenia soap

**Comment by leszcz** [comment]
Hej, tak jak pisałem - mimo instalacji SOAP nie działało. 
Zrestartowałem serwer hard-resetem i przeszło. 
Przy okazji - @johnzuk założyć nowy issue w wypadku odpowiedzi będącej nullem z serwera GUS?

**Comment by johnzuk** [comment]
@leszcz Wystarczy to które jest obecnie - potrzebuję tam tylko więcej detali :)
