### ISSUE TITLE
Wsparcie dla PHP 7.4

### ISSUE THREAD

**Issue by cve** [johnzuk/GusApi#89]
Cześć,

przede wszystkim dzięki wielkie za fajną bibliotekę, ale natknąłem się na problem w PHP w wersji 7.4 dostaję taki log:

request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP)" at {path}/vendor/gusapi/gusapi/src/GusApi/Client/Builder.php line 54 {"exception":"[object] (ErrorException(code: 0): Warning: Use of undefined constant SOAP_1_2 - assumed 'SOAP_1_2' (this will throw an Error in a future version of PHP) at {path}/vendor/gusapi/gusapi/src/GusApi/Client/Builder.php:54)"} []

**Comment by konradkalemba** [comment]
Właśnie natknąłem się na ten sam problem. Wersja PHP: `7.2.24`

**Comment by johnzuk** [comment]
Wygląda na brak rozszerzenia SOAP

**Comment by cve** [comment]
Faktycznie miałem coś popierdzielone z wersjami rozszerzeń do php na serwerze, dzięki wielkie.
